name: customer_v1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  shared_preferences: ^2.0.6
  firebase_core: ^1.10.6
  firebase_crashlytics: ^2.2.1
  firebase_auth: ^3.0.1
  cloud_firestore: ^3.1.6
  image_picker:
  firebase_storage: ^10.0.1
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  #provider: ^5.0.0
  url_launcher: ^6.0.2
  intl: ^0.17.0
  cached_network_image: ^3.1.0
  uuid: ^3.0.4
  #  video_thumbnail:
  video_thumbnail: ^0.4.3
  path_provider: ^2.0.2
  photo_view: ^0.12.0
  video_player: ^2.1.12
  flutter_facebook_auth: ^3.5.0
  http: ^0.13.3
  # geolocator: ^7.3.1
  latlong2: ^0.8.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  firebase_messaging: ^11.2.4
  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^7.3.0
  permission_handler: ^6.0.1
  easy_localization: ^3.0.0
  transparent_image: ^2.0.0
  mime: ^1.0.0
  moor_flutter: ^4.0.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.0
  # google_maps_flutter: ^2.0.6
  #  stripe_payment:
  #  stripe_payment: ^1.1.4
  font_awesome_flutter: ^9.1.0
  flutter_polyline_points: ^1.0.0
  percent_indicator: ^3.0.1
  lottie: ^1.1.0
  flutter_native_image: ^0.0.6+1
  video_compress: ^3.1.0
  flutter_sound: ^8.3.9
  the_apple_sign_in: ^1.1.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  dotted_border: ^2.0.0+1
  rename: ^1.3.1
  country_picker: ^2.0.8
  flutter_braintree: ^2.0.0+1
  flutter_staggered_animations: ^1.0.0
  loadmore: ^2.0.1
  flutter_rating_bar: ^4.0.0
  # extended_list: ^3.0.0
  # loadmore: ^2.0.1
  # infinite_widgets: ^2.0.0
  # google_maps_place_picker: ^2.1.0-nullsafety.0
  google_maps_place_picker:
  google_maps_flutter:
  geolocator: ^7.0.1
  google_maps_webservice:
  geocoding: ^2.0.1
  share: ^2.0.4
  flutter_staggered_grid_view: ^0.4.1
  # flutter_google_places: ^0.3.0
  wc_flutter_share: ^0.4.0
  clipboard: ^0.1.3
  flutter_neumorphic: ^3.2.0
  geoflutterfire: ^3.0.2
  get:
  mercadopago_sdk: ^1.3.0
  location:

  flutter_stripe: ^2.1.1
  flutter_facebook_keyhash: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^4.4.1
  build_runner: ^2.0.6

  flutter_lints: ^1.0.0


# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/

  fonts:
    - family: Poppinsb
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppinsl
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppinsm
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppinsr
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppinssb
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf


